version: 2.1

jobs:
  test:
    docker:
      - image: python:3.10  # Use Python 3.9 for your tests
    executor:
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install pytest pytest-cov coveralls
      - run:
          name: Set environment variable and Run tests with coverage
          command: |
            export OPENAI_API_KEY="$OPENAI_API_KEY"  
            source venv/bin/activate
            python main.py & 
            source venv/bin/activate
            pytest --cov=. test_tutor.py
            coverage report -m
      - run:
          name: Upload coverage to Coveralls
          command: |
            source venv/bin/activate
            pip install coveralls
            coveralls

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
